### ISSUE TITLE
LINK WITH GTU

### ISSUE THREAD

**Issue by 1Crazymoney** [Permissionless-Software-Foundation/community-committee#18]
I WOULD LIKE TO LINK MY gtu ON MEMO.CASH- INSTRUCTIONS- DOCUMENTS PLEASE.

**Comment by christroutner** [comment]
There are no instructions at this time. It would require a skilled JavaScript developer to modify the token-liquidity app. This may or may not happen in the future. The best thing is to stay tuned to our [Telegram channel](https://t.me/permissionless_software).
