### ISSUE TITLE
PSF Technical Steering Committee Meeting 2020-12-23

### ISSUE THREAD

**Issue by christroutner** [Permissionless-Software-Foundation/community-committee#3]
This Issue was mis-posted. Here is the correct Issue for tracking the TSC meeting:

https://github.com/Permissionless-Software-Foundation/TSC/issues/1

**Comment by pcmasterclass** [comment]
bitcoincash:qp3hvpsgewnnfhaw3879cm785elmgfmemq9qf3eya3
